INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('CAIXA DE TEXTO'); --> 0

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('ÁREA DE TEXTO'); --> 1

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('CAIXA DE CHECAGEM'); --> 2

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('LISTA DE VALORES'); --> 3

