INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('CAIXA DE TEXTO');

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('ÁREA DE TEXTO');

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('CAIXA DE CHECAGEM');

INSERT INTO COMPONENT_TYPE (TIPO) 
VALUES ('LISTA DE VALORES');

