CREATE TABLE Peca (
	id			INTEGER IDENTITY PRIMARY KEY,
	descricao	VARCHAR(500),
	categoria	VARCHAR(100),
	tipo		VARCHAR(100),
	imagem		LONGVARBINARY,
	status		VARCHAR(70),
	preco		DOUBLE
);

ALTER TABLE PECA
ADD COLUMN QTD_ESTOQUE INTEGER;


CREATE TABLE TIPO_PECA (
	ID INTEGER IDENTITY PRIMARY KEY,
	TIPO VARCHAR(300)
);

INSERT INTO TIPO_PECA (TIPO) VALUES
	 ('Cordão'),
	 ('Pulseira'),
	 ('Brinco'),
	 ('Anel'),
	 ('Relógio');


CREATE TABLE mensagem (
	id			INTEGER IDENTITY PRIMARY KEY,
	nome		VARCHAR(500),
	email		VARCHAR(300),
	telefone	VARCHAR(11),
	mensagem	VARCHAR(1500),
	status		INTEGER DEFAULT 1,
	data		DATE
);

CREATE TABLE USUARIOS (
    ID BIGINT PRIMARY KEY IDENTITY,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP
);

CREATE TABLE telefone (
    id BIGINT PRIMARY KEY IDENTITY,
    numero VARCHAR(20)
);

CREATE TABLE ENDERECO (
    id BIGINT PRIMARY KEY IDENTITY,
    rua VARCHAR(100),
    numero VARCHAR(20),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado VARCHAR(2),
    cep VARCHAR(10),
    telefone_id BIGINT,
    CONSTRAINT fk_telefone
        FOREIGN KEY (telefone_id)
        REFERENCES telefone(id)
);

ALTER TABLE ENDERECO
ADD USUARIO_ID BIGINT

ALTER TABLE ENDERECO
ADD CONSTRAINT FKU FOREIGN KEY(USUARIO_ID)
REFERENCES USUARIOS(ID)

ALTER TABLE ENDERECO
ADD COMPLEMENTO VARCHAR(150)








