CREATE TABLE LINK (
	ID INTEGER auto_increment PRIMARY KEY,
	DESCRICAO  VARCHAR(500),
	URL        VARCHAR(950),
	CRP 	   VARCHAR(300)
);

CREATE TABLE CO (
	ID INTEGER auto_increment PRIMARY KEY,
	NOME  VARCHAR(300)
);

